-- Rollback RLS policies.
DROP FUNCTION IF EXISTS app.is_workspace_member(uuid);
DROP SCHEMA IF EXISTS app CASCADE;

-- Disable RLS on all tables (not strictly needed since 001 down drops them).
ALTER TABLE IF EXISTS profiles          DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS workspaces        DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS workspace_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS refresh_tokens    DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS email_tokens      DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS products          DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS product_variants  DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS product_channel_overrides DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS inventory_items   DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS inventory_adjustments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS orders            DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS order_items       DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS order_status_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS channel_order_refs  DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS customers         DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS customer_notes    DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS transactions      DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS income_entries    DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS expense_entries   DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS receivables       DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS payment_records   DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS bank_transfers    DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ai_usage          DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS einvoices         DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS einvoice_line_items DISABLE ROW LEVEL SECURITY;
